spring.application.name=AuthService
spring.profiles.active=test

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

jwt.keystore.path=keystore.p12
jwt.keystore.password=superhardpassword
jwt.keystore.alias=auth-key
jwt.access-token.expiration=432000
jwt.refresh-token.expiration=6480000

internal.secret=super-secret-internal
internal.secret.header=X-Internal-Secret